### ISSUE TITLE
Custom vapor's working dir issue!

### ISSUE THREAD

**Issue by diuming** [vapor-community/Lingo-Vapor#11]
Vapor 4.0
macOS 10.15.6

I set vapor's working dir manual.
`app.directory = DirectoryConfiguration(workingDirectory: "/some/place/i/prefer")`
and then
`app.lingoVapor.configuration = .init(defaultLocale: "en")`

Does it support custom working dir?

error
-----
error":true,"reason":"Error Domain=NSCocoaErrorDomain Code=260 \"The folder “Localizations” doesn’t exist.\"

**Comment by NathanFallet** [comment]
Is your folder placed at `/some/place/i/prefer/Localizations`? (this should be the expected behaviour, verify that it is not inside a subfolder like `Resources` or whatever else)
