### ISSUE TITLE
LocaleIdentifier should use "-" instead of "_"

### ISSUE THREAD

**Issue by th-mustache-dk** [vapor-community/Lingo-Vapor#12]
According to the RFC, locale identifiers in headers uses "-"  to separate language from country code

https://httpwg.org/specs/rfc7231.html#header.accept-language

Therefore the code should be corrected to use "-"

Perhaps some logic from https://github.com/matsoftware/accept-language-parser can be used.

**Comment by miroslavkovac** [comment]
Hi @th-mustache-dk, the "_" in locale identifiers were from iOS world :) Please check the version 4.2.0 where this is now fixed. Thanks for reporting an issue!
