### ISSUE TITLE
QUESTION: How do i get the locale of the user

### ISSUE THREAD

**Issue by sadiq81** [vapor-community/Lingo-Vapor#8]
I'm making a custom tag for leaf and i cant figure out how get the requests current locale?

**Comment by miroslavkovac** [comment]
I can imagine that this largely depends on how you have implemented the locale:
- some websites have it in the subdomain (like en.wikipedia.org, fr.wikipedia.org)
- some have it in the path (www.wikipedia.org/en/.., www.wikipedia.org/fr/...)
- some keep it in the session/db and allow user to change it
- some query the Accept-Language header of the request.

Depending on which way you choose to implement locale, there will be a different way of getting the locale for you user.

**Comment by hadig** [comment]
geo locate user ip

**Comment by miroslavkovac** [comment]
Closing this issue after long period of inactivity and given that many solutions are suggested.
